[package]
name = "ya-sb-router"
version = "0.6.1"
description = "Service Bus Router"
authors = ["Golem Factory <contact@golem.network>"]
homepage = "https://github.com/golemfactory/ya-service-bus/crates/router"
repository = "https://github.com/golemfactory/ya-service-bus"
license = "GPL-3.0"
edition = "2021"

[features]
default = []
bin = ['env_logger', 'tokio/signal', 'humantime', "log/release_max_level_debug"]

[lib]
name = "ya_sb_router"
path = "src/lib.rs"

[[bin]]
name = "ya-sb-router"
path = "src/bin.rs"
required-features = ['bin']

[dependencies]
ya-sb-proto = { workspace = true }
ya-sb-util = { workspace = true, features = ["with-writer"] }
actix-rt = { workspace = true }
actix = { workspace = true, default-features = false, features = ["macros"] }
actix-server = { workspace = true }
actix-service = { workspace = true }

anyhow = { workspace = true }
chrono = { workspace = true }

futures = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
prost = { workspace = true }
structopt = { workspace = true }
tokio = { workspace = true, features = ["net", "sync", "macros", "rt-multi-thread", "time"] }
tokio-util = { workspace = true, features = ["codec"] }
tokio-stream = { workspace = true, features = ["sync"] }
url = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
parking_lot = { workspace = true }
bitflags = { workspace = true }
pin-project = { workspace = true }
humantime = { workspace = true, optional = true }
env_logger = { workspace = true, optional = true }

[dev-dependencies]
ubyte = "0.10.1"

[package.metadata.deb]
features = ["bin"]
maintainer-scripts = "debian/"
systemd-units = { enable = false }
assets = [
    ["target/release/ya-sb-router", "usr/bin/", "755"],
    ["debian/ya-sb-router.conf", "etc/", "644"]
]
conf-files = [
    "/etc/ya-sb-router.conf"
]
