[package]
name = "ya-sb-router"
version = "0.4.1"
description = "Service Bus Router"
authors = ["Golem Factory <contact@golem.network>"]
homepage = "https://github.com/golemfactory/ya-service-bus/crates/router"
repository = "https://github.com/golemfactory/ya-service-bus"
license = "GPL-3.0"
edition = "2018"

[features]
default = []
bin = ['env_logger', 'tokio/signal', 'humantime', "log/release_max_level_debug"]

[lib]
name = "ya_sb_router"
path = "src/lib.rs"

[[bin]]
name = "ya-sb-router"
path = "src/bin.rs"
required-features = ['bin']

[dependencies]
ya-sb-proto = { version = "^0.3", path = "../proto" }
ya-sb-util = { version = "0.2", path = "../util", features = ["with-writer"] }
actix-rt = "2.2"
actix = { version = "0.11", default-features = false, features = ["macros"] }
actix-server = "=2.0.0-beta.4"
actix-service = "=2.0.0-beta.5"

anyhow = "1.0.28"
chrono = "0.4"

futures = "0.3"
lazy_static = "1.4"
log = "0.4.8"
prost = "0.7.0"
structopt = "0.3"
tokio = { version = "1.6", features = ["net", "sync", "macros", "rt-multi-thread", "time"] }
tokio-util = { version = "0.6", features = ["codec"] }
tokio-stream = { version = "0.1", features = ["sync"] }
url = "2.1.1"
uuid = { version = "0.8.1", features = ["v4"] }
parking_lot = "0.11.1"
bitflags = "1.2.1"
pin-project = "1.0.7"
humantime = { version = "2.1.0", optional = true }
env_logger = { version = "0.8", optional = true, default-features = false }

[package.metadata.deb]
features = ["bin"]
maintainer-scripts = "debian/"
systemd-units = { enable = false }
assets = [
    ["target/release/ya-sb-router", "usr/bin/", "755"],
    ["debian/ya-sb-router.conf", "etc/", "644"]
]
conf-files = [
    "etc/ya-sb-router.conf"
]
