[package]
name = "ya-sb-router"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4.12"
failure = "0.1.6"
lazy_static = "1.4.0"
prost = "0.5.0"
tokio = "0.1.22"
ya-sb-api = { path = "../api" }
