[package]
name = "ya-sb-router"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
ya-sb-proto = "0.1"
ya-sb-util = "0.1"

bytes = "0.4.12"
failure = "0.1.6"
futures = { version = "0.3", features = ["compat"] }
lazy_static = "1.4.0"
prost = "0.5.0"
structopt = "0.3"
tokio = "0.1.22"
uuid = { version = "0.8.1", features = ["v4"] }
