[package]
name = "ya-service-bus"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
ya-sb-proto = "0.1"
ya-sb-util = "0.1"

actix = "0.9"
failure = "0.1"
futures = "0.3"
lazy_static = "1.4"
log = "0.4"
rand = "0.7.2"
rmp-serde = "0.14.0"
serde = { version = "1.0.102", features = ["derive"] }
tokio = { version = "0.2.6", features = ["tcp", "time"] }
tokio-util = "0.2.0"

[dev-dependencies]
actix-rt = "1.0"
env_logger = "0.7"
serde_json = "1.0"
structopt = "0.3.5"
