[package]
name = "ya-service-bus"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[features]
default = ["with-actix"]
with-actix = ["futures_01"]

[dependencies]
ya-sb-proto = "0.1"
ya-sb-util = "0.1"

actix = "0.8.3"
failure = "0.1"
futures = { version = "0.3", features = ["compat"] }
lazy_static = "1.4"
log = "0.4"
rand = "0.7.2"
rmp-serde = "0.14.0"
serde = { version = "1.0.102", features = ["derive"] }
tokio-codec = "0.1"
tokio-tcp = "0.1"

[dependencies.futures_01]
version = "0.1.25"
optional = true
package = "futures"

[dev-dependencies]
env_logger = "0.7"
serde_json = "1.0"
structopt = "0.3.5"
tokio-timer = "0.1"
