[package]
name = "ya-sb-proto"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[features]
default = ["with-codec"]
with-codec = ['tokio-util']

[dependencies]
ya-sb-util = "0.1"

bytes = "0.4"
failure = "0.1.6"
prost = "0.5.0"
tokio-bytes = { version = "0.5", package = "bytes" }
tokio-util = { version = "0.2", optional = true, features = ["codec"] }

[build-dependencies]
prost-build = "0.5.0"
