[package]
name = "ya-sb-api"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
failure = "0.1.6"
prost = "0.5.0"

[build-dependencies]
prost-build = "0.5.0"
